### ISSUE TITLE
Text is disappearing as I type rapidly

### ISSUE THREAD

**Issue by sarguido** [atecce/www#2]
Browser: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
OS: Mojave 10.14

![disappearing text](https://user-images.githubusercontent.com/3422080/53667368-d32b9b00-3c3e-11e9-84bb-0a24a8f5245b.gif)

**Comment by atecce** [comment]
![mar-02-2019 14-06-06](https://user-images.githubusercontent.com/10567112/53686399-78ed1180-3cf4-11e9-9ff2-58150814d92c.gif)

lgtm but idk

**Comment by sarguido** [comment]
Closing FOR NOW.
