### ISSUE TITLE
Overlapping text in bar chart

### ISSUE THREAD

**Issue by sarguido** [atecce/www#4]
<img width="434" alt="screen shot 2019-03-01 at 4 37 45 pm" src="https://user-images.githubusercontent.com/3422080/53667906-62857e00-3c40-11e9-8d8e-698da37d3fd2.png">

**Comment by atecce** [comment]
should be fixed by https://github.com/atecce/www/pull/5

**Comment by atecce** [comment]
<img width="151" alt="screen shot 2019-03-02 at 2 41 04 pm" src="https://user-images.githubusercontent.com/10567112/53686756-38dc5d80-3cf9-11e9-898c-ad911fb31f7a.png">
